# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 291a9c892ba7e57369d8b2cb697c73d2cf2de4e0ffa2fcea1c1c2de9d56534d51c2a1c7f5460e303b9d7fa3ee9415141b87669305e22dd43d8854cb6aaaca799

test:
  secret_key_base: baf0760beac5933fb2f03fb34c641124db3b66ba1c3019df7c0f87396efaf5bd703b9222506893f321d2920caa3b76233a1005d06738a773d458a788b499c148

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
